### ISSUE TITLE
offline mode error

### ISSUE THREAD

**Issue by AhmedKazlak** [ml4bio/Dense-Homolog-Retrieval#10]
Hello, team.

Thanks a lot for your great efforts and work.

I am trying to create an offline database, but I keep receiving this error when running the do_agg.py script. Could you please advise?

[2024-08-26 18:17:28,414][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpov3120kz
[2024-08-26 18:17:28,414][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpov3120kz/_remote_module_non_sriptable.py
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
xxxx/conda-environments/fastMSA/lib/python3.8/site-packages/torch/utils/data/dataloader.py:487: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 3, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
xxxx/conda-environments/fastMSA/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:659: UserWarning: Your `predict_dataloader` has `shuffle=True`, it is strongly recommended that you turn this off for val/test/predict dataloaders.
  rank_zero_warn(
Predicting: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:43<00:00,  2.06s/it]
Traceback (most recent call last):
  File "do_agg.py", line 31, in <module>
    lst, vec = torch.load(os.path.join(embdb_path, rank, pts))
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by heathcliff233** [comment]
Hello, thanks for the bug report. The codebase has been updated and this should be fixed. Please try to pull again.
