### ISSUE TITLE
Results' validity

### ISSUE THREAD

**Issue by AhmedKazlak** [ml4bio/Dense-Homolog-Retrieval#14]
Hello, team.

Thanks a lot for such a great work.

According to the latest version on GitHub, the [do_retrieval.py](https://github.com/ml4bio/Dense-Homolog-Retrieval/blob/main/do_retrieval.py) script outputs the predictions in the _/db/_ directory and doesn't generate the _/res/_ or _/seq/_ directory since `my_align` and `gen_query` are commented.

While manipulating the `-n` argument, the code generates the provided number regardless of true homology. For instance, I built an offline dataset of 200M proteins, and when I set `-n` to 200M, all of the proteins in this database were predicted as homologs.

Do you have an insight into what I might be doing wrong? Does filtration happen at the `qjackhammer` step, and since it is commented, does the pipeline not function as expected?

**Comment by hml1996-fight** [comment]
I have a same problem. I built an offline dataset of 29421 (example/df-ebd.tsv), and when I set `-n` to 400000, the result file have 400000 sequences. But the database I built only have 29421 sequences.  What's wrong?

**Comment by heathcliff233** [comment]
Thank you for your question. As for the -n option, it is used to retrieve the top ranked sequences instead of *ground truth* homologs. You may regard the scores returned by the faiss search as the bit scores in HMMER, which measures the similarity. Though homolog itself should be something like sharing ancestry, but in computational definition, it is regarded as surviving the test of homologous vs random. If you have tried out Pfam, they have a gathering threshold for all families. In your case, you may set a cutoff score like 60 in v1 branch to get those with higher score.
As for the second question, it is due to the features in faiss package (it should be filling the else with duplicated ones). Maybe I should add a notice or a check in the script. Thank you for the reminder.

**Comment by AhmedKazlak** [comment]
Thanks a lot, @heathcliff233, for your answer.

I modified [do_retrieval.py](https://github.com/ml4bio/Dense-Homolog-Retrieval/blob/main/do_retrieval.py) to generate the scores accounting for the 2D nature of results and filter based on the score as you suggested.

```
for i in range(math.ceil(encoded.shape[0] / search_batch)):
    scores, idxes = index.search(encoded[i * search_batch:(i + 1) * search_batch], tar_num)
    for j in range(len(idxes)):
        results = []
        for k in range(len(scores[j])):
            tar_idx = idxes[j][k]
            score = scores[j][k]
            res = df.iloc[tar_idx]
            seq_id = res['id']
            results.append({'id': seq_id, 'score': score})
            
        results_df = pd.DataFrame(results)
        print(results_df)
```

I noticed that the scores increase with the increase in the retrieved homologs, hitting the highest values when using the complete dataset instead of a fixed number.
```
df = pd.read_pickle(dm_path)
tar_num= len(df)
```
This showcases the results using a `tar_num` equal to the length of the search database. (9M in this case.)
![image](https://github.com/user-attachments/assets/b47ffa04-5bae-4cce-9b69-d585104bd142)

This showcases the results using a `tar_num` equal to 50 using the same query and database.
![image](https://github.com/user-attachments/assets/83fdea92-6699-4dda-a978-6d0b7dcbb31f)

I have two questions.
1- Does the model retrieve the closest homologs from the complete database when assigned a value like 50? If so, why do the 50 homologs have significantly lower scores than retrieving the whole database? What do you think is the right approach?
2- Are these scores database-dependent? This means that if I had to split a 500M-sequence database into 10M chunks due to memory constraints, would retrieving from each chunk be as efficient as retrieving from the 500M sequence if they were in a single pkl/index file?

Thanks a lot for your time and input.

**Comment by heathcliff233** [comment]
Thank you for your question. I think I need to add more detailed explanations to the scores, ranking and all other options. DHR is actually doing ranking here, which means it will rank all the sequences in the database from the most homologous to least (aka random sequence). The `tar_num` here mainly assists in retrieving the top `tar_num` of candidate homologs and these sequences are ranked by the score calculated from query and database sequence embeddings.
As for Q1, by setting `tar_num=50` DHR retrieves the top 50 candidate homologs from the database. If you would like to set a score threshold, (75 for example), you should first set a relatively large `tar_num`, and then add one more filter on the score to keep only those scores under 75. Here the score means the L2 distance between embeddings. 
As for Q2, the scores are not database-dependent so long as you are using the FlatL2 for faiss index construction. The score is directly calculated from a pair of query and the database sequence. As for the memory consumption issue, I will try to add more tutorials on optimizing faiss.

**Comment by AhmedKazlak** [comment]
Thanks a lot, @heathcliff233, for the clarification; this helps a lot.

Regarding the splitting, I initially used 50 GPU nodes to accelerate the embeddings' generation and currently have 50 predictions.pt files corresponding to each chunk. I wonder if do_agg.py can index them into a single file since loading all of them in the memory isn't feasible.

**Comment by heathcliff233** [comment]
@AhmedKazlak Yes I believe so. Please refer to  https://github.com/ml4bio/Dense-Homolog-Retrieval/blob/4305a6031d757fe624c58e837b923fd80fb7a4f6/do_agg.py#L32 . Here I have already implemented the way it should aggregate when using multiple GPUs for embedding. I am not sure of yours but should be able to convert into a similar directory structure. However, indexing all of them into one file still requires loading to memory and makes no difference to the memory usage (aggregation needs reading all of them). Previsouly, when dealing with billion-level databases, I will cluster the database first and build other indexes using inverted list etc. to minimize memory usage. If you insists on using Flat index for highest accuracy, please refer to this faiss official demo.
https://github.com/facebookresearch/faiss/blob/main/demos/demo_ondisk_ivf.py
