### ISSUE TITLE
How to use this software?

### ISSUE THREAD

**Issue by lpyhhh** [ml4bio/Dense-Homolog-Retrieval#16]
Does this software have a trained model? Why does the following error appear when I run python3 do_retrieval.py -i /home/ubuntu/Virus/Clstr103789 -d /home/ubuntu/Virus/emb/ -o ../Result?
![image](https://github.com/user-attachments/assets/ee2cfa35-e7b1-4e21-9968-41af7303d17a)

**Comment by lpyhhh** [comment]
command：python3 do_retrieval.py -i /home/ubuntu/Virus/Clstr103789 -d /home/ubuntu/Virus/emb/ -o ../Result

**Comment by heathcliff233** [comment]
Hello, please refer to the build environment section and download the checkpoints.
