### ISSUE TITLE
Please add a license file!

### ISSUE THREAD

**Issue by zdk123** [ml4bio/Dense-Homolog-Retrieval#3]
Github repos should have a license so that users know how they are allowed to use your code

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

thank you!

**Comment by heathcliff233** [comment]
Thank you for reminding. The license has been added.
