### ISSUE TITLE
error

### ISSUE THREAD

**Issue by editSeqDesign** [ml4bio/Dense-Homolog-Retrieval#4]
![图片](https://github.com/user-attachments/assets/69234bf2-5d2d-4a6a-8ce9-82ff3d11b5b5)
![图片](https://github.com/user-attachments/assets/438b91ac-8487-4e84-a45c-4331f34850e1)
use this  customized Phylopandas, but error

**Comment by heathcliff233** [comment]
Thanks for trying the repo. It should be due to hard coding of phylopandas path. By moving the phylopandas directory of it into dhr repo should solve the issue. I am currently working on removing the dependency.

**Comment by heathcliff233** [comment]
The dependency has been removed. Please try to pull again. Thank you.
