### ISSUE TITLE
build env error

### ISSUE THREAD

**Issue by aysmeteor** [ml4bio/Dense-Homolog-Retrieval#7]
<img width="725" alt="env error" src="https://github.com/user-attachments/assets/6bd4e1d9-ac9f-40d6-b824-229ec41bbcd7">

**Comment by heathcliff233** [comment]
Thanks for trying. I have updated the yaml file. Would you please pull and try again?

**Comment by aysmeteor** [comment]
![image](https://github.com/user-attachments/assets/1b10a1d7-7bb2-453e-ac3e-e3ce5a1f5521)
The previous error was resolved successfully, but there is still new error here.
