### ISSUE TITLE
Reproduce problem

### ISSUE THREAD

**Issue by wakawaka111** [ml4bio/Dense-Homolog-Retrieval#8]
Hi, when I attempted to replicate the experimental results on the SCOPe benchmark, I found significant inconsistencies. When using biencoder's forward_left function during do_retrieval and biencoder's forward_right function during do_embedding, the AUC-1FP was only 0.171, and the dimension of the generated dense embeddings was 480 instead of the 768 mentioned in the paper. Could you please help us identify where the issue might be and if the weights might have been uploaded incorrectly? Thank you for your response.

**Comment by heathcliff233** [comment]
Hi, thank you for your question. Would you please first make sure that the checkpoint is properly loaded? As for the other questions, the benchmark was done using the v1 branch with esm1, so the dim is 768 while the main branch was required by reviewer to scale up and use esm2. Please try v1 branch for scope reproduction.
As for the AUC-1FP metric, we follow the definition of previous methods to not regard those sequences being in the same super class as negative.
If you have further problems, please feel free to drop me an email at liang.hong@link.cuhk.edu.hk
