### ISSUE TITLE
Based on the main branch environment, what will happen to the res.phylo.to_fasta_ dev (os. path. join (out_cath, "db", names [i * search_datch+j]+'. fasta') method of phylopandas

### ISSUE THREAD

**Issue by editSeqDesign** [ml4bio/Dense-Homolog-Retrieval#9]
Based on the main branch environment, what will happen to the res.phylo.to_fasta_ dev (os. path. join (out_cath, "db", names [i * search_datch+j]+'. fasta') method of phylopandas
File "/hpcfs/fhome/xxxx/.conda/envs/dprv3/lib/python3.9/site-packages/phylopandas/seqio/write.py", line 183, in _write    
     seq_records.to_csv(filename, sep='\n', header=False, index=False, line_terminator='\n>', mode='a+')
TypeError: to_csv() got an unexpected keyword argument 'line_terminator'

**Comment by heathcliff233** [comment]
Thank you for the report. Currently I have removed the dependency on phylopandas due to numerous compatibility issue and supports tsv format input. Please try to pull again.
The problem you see here is probably due to different args in different pandas version.
